POST http://localhost:3000/api/anime
Content-Type: application/json

{
    "name": "SNK"
}

###

GET http://localhost:3000/api/anime

###

PATCH http://localhost:3000/api/anime
Content-Type: application/json

{
    "id": 8,
    "name": "Shingeki no Kyojin"
}

###

DELETE http://localhost:3000/api/anime
Content-Type: application/json

{
    "id": 9
}