POST http://localhost:3000/animes
Content-Type: application/json

{
    "name": "One Punch Man"
}

###

GET http://localhost:3000/animes

###

PATCH http://localhost:3000/animes/8
Content-Type: application/json

{
    "name": "Shingeki no Kyojin"
}

###

DELETE http://localhost:3000/animes/10
